export const SET_JOBS_LOGIN = 'SET_JOBS_LOGIN';
export const SET_JOBS_REGISTER = 'SET_JOBS_REGISTER';
export const SET_JOBS_FORGOT_PASSWORD = 'SET_JOBS_FORGOT_PASSWORD';
export const CHECK_SUCCESS_SAVE_ACCOUNT = 'CHECK_SUCCESS_SAVE_ACCOUNT';
export const CHECK_FALSE_SAVE_ACCOUNT = 'CHECK_FALSE_SAVE_ACCOUNT';