export const SET_JOBS_LOGIN = 'SET_JOBS_LOGIN';
export const SUCCESS_JOBS_LOGIN = 'SUCCESS_JOBS_LOGIN';
export const FALSE_JOBS_LOGIN = 'FALSE_JOBS_LOGIN';
export const ERROR_JOBS_LOGIN = 'ERROR_JOBS_LOGIN';
export const BAN_JOBS_LOGIN = 'BAN_JOBS_LOGIN';
export const LOCK_JOBS_LOGIN = 'LOCK_JOBS_LOGIN';

export const SET_JOBS_REGISTER = 'SET_JOBS_REGISTER';
export const SET_JOBS_FORGOT_PASSWORD = 'SET_JOBS_FORGOT_PASSWORD';
export const CHECK_SUCCESS_SAVE_ACCOUNT = 'CHECK_SUCCESS_SAVE_ACCOUNT';
export const CHECK_FALSE_SAVE_ACCOUNT = 'CHECK_FALSE_SAVE_ACCOUNT';