export const SET_JOBS_LOGIN = 'SET_JOBS_LOGIN';
export const SUCCESS_JOBS_LOGIN = 'SUCCESS_JOBS_LOGIN';
export const FALSE_JOBS_LOGIN = 'FALSE_JOBS_LOGIN';
export const ERROR_JOBS_LOGIN = 'ERROR_JOBS_LOGIN';
export const BAN_JOBS_LOGIN = 'BAN_JOBS_LOGIN';
export const LOCK_JOBS_LOGIN = 'LOCK_JOBS_LOGIN';

export const SET_JOBS_REGISTER = 'SET_JOBS_REGISTER';
export const SET_JOBS_FORGOT_PASSWORD = 'SET_JOBS_FORGOT_PASSWORD';
export const CHECK_SUCCESS_SAVE_ACCOUNT = 'CHECK_SUCCESS_SAVE_ACCOUNT';
export const CHECK_FALSE_SAVE_ACCOUNT = 'CHECK_FALSE_SAVE_ACCOUNT';

export const FETCH_ACCOUNT_ME = 'FETCH_ACCOUNT_ME';
export const FETCH_ACCOUNT_ME_SUCCESS = 'FETCH_ACCOUNT_ME_SUCCESS';
export const FETCH_ACCOUNT_ME_ERROR = 'FETCH_ACCOUNT_ME_ERROR';

export const SET_AVATAR_ACCOUNT = 'SET_AVATAR_ACCOUNT';
export const ERR_AVATAR_ACCOUNT = 'ERR_AVATAR_ACCOUNT';

export const GET_AVATAR_ACCOUNT_SUCC = 'GET_AVATAR_ACCOUNT_SUCC';
export const GET_AVATAR_ACCOUNT_ERR = 'GET_AVATAR_ACCOUNT_ERR';

export const SET_PASSWORDS_SUCCESS = 'SET_PASSWORDS_SUCCESS';
export const SET_PASSWORDS_FALSE = 'SET_PASSWORDS_FALSE';
export const SET_PASSWORDS_ERROR = 'SET_PASSWORDS_ERROR';